### ISSUE TITLE
Masteries and Runes possible bug

### ISSUE THREAD

**Issue by dukevomv** [claudiowilson/LeagueJS#32]
I seem to have a problem retrieving the masteries and runes after the last update.
I tried all the "LolApi.Summoner..." functions and for some reason getMasteries() and getRunes() does not work for me. They return undefined as result and null as error.

Im using the 'eune' server.

**Comment by claudiowilson** [comment]
I'll check it out!

**Comment by claudiowilson** [comment]
fixed it in the latest version :)

**Comment by dukevomv** [comment]
Appreciate it! Thank you
