### ISSUE TITLE
Seems to be an issue with getPlayerSummary()

### ISSUE THREAD

**Issue by MonoHearted** [claudiowilson/LeagueJS#34]
>events.js:72
>       throw er; // Unhandled 'error' event
>              ^
>Error: getaddrinfo ENOTFOUND
>    at errnoException (dns.js:37:11)
>    at Object.onanswer [as oncomplete] (dns.js:124:16)

is being returned from: 

```javascript
LolApi.init(leagueKey);
LolApi.Stats.getPlayerSummary(sumId, 2015, region, function(error, out) {
...
}
```

Which I found quite interesting. Dug through the api, I couldn't find the cause – However, I don't think it's an issue with my coding, as even an empty api call here returns that error. (sumId, region are defined above as parameters.) I saw that in util.js `getValidSeasonParam` used ===, so I tried both 2015 as an integer and a string – neither worked. I even tried it as an array, as the README suggested.

**Comment by jhgaylor** [comment]
I use the client with promise and not callbacks, so ymmv, but I just checked some of my code that uses this library and this is what I have.

```js
// grab the library
var LolApi = require('leagueapi');
// initialize with my key and for region 'na'
LolApi.init(process.env.LOL_API_KEY, 'na');
// make a request and process the result
LolApi.Summoner.getByName(summoner_name, region).then(function (data) {
  var id = data && data[summoner_name].id;
});
```

Could you tell us more about the value in sumId and region?

**Comment by EldoranDev** [comment]
i think this issue can be closed
