### ISSUE TITLE
Region error not catched

### ISSUE THREAD

**Issue by tedcurrent** [claudiowilson/LeagueJS#40]
Hey,

How would you suggest catching non-existing regions? For example, `LolApi.Summoner.getByName `catches a non-existing summoner name but not region. I get:
Error: getaddrinfo ENOTFOUND nas.api.pvp.net nas.api.pvp.net:443

And I can't catch it with `if (err)`. It just breaks.

I can of course check the input region on server side to ensure that the region exists, but having an error thrown here would simplify things.

Cheers,
tedcurrent

**Comment by EldoranDev** [comment]
Made it an library error with #41 we additonaly could add a new error type for not existing regions.

**Comment by claudiowilson** [comment]
Merged #41, this should produce an error in the callback

**Comment by tedcurrent** [comment]
Thanks guys!
