### ISSUE TITLE
Add possibility for array as Data option where possible

### ISSUE THREAD

**Issue by Colorfulstan** [claudiowilson/LeagueJS#50]
Currently methods that accept a parameter for which Data is returned by RIOT (like getItemList, getItemById, ...) only accept a string for the respective option. But RIOT Api allows for multiple options.

Methods should be updated acchordingly. I did it for two of them Im currently using:
https://github.com/claudiowilson/LeagueJS/pull/49/commits/4f0978f76c2d385a2716e86a1a59adaba7e5b5ed

**Comment by MarcusMann** [comment]
What to put in the callback parameter?

**Comment by Colorfulstan** [comment]
Would you mind explaining how this is relevant to the issue?
I don't understand the question in this context.

**Comment by EldoranDev** [comment]
We could implement every method like @Colorfulstan did in #58.

If this project is still maintained/used we should reimplement some functions to work both ways with arrays and with strings

**Comment by Colorfulstan** [comment]
The question would be if it's worth it or if it would be better to switch to another library that already implements those things. I decided to use this for my project because of the ease to use it.

The points that would be in need of some form of change would be imo:
1) accepting arrays as arguments where intended by riot 
2) accepting arrays as Data option as I mentioned in this issue
3) changing error-handling to be more flexible and actually exposing the response-object in addition to the constructed string to make error-handling within the application easier.
4) Exposing the error-response would make it possible to use the new headers from Riot when neccessary [see here](https://developer.riotgames.com/docs/rate-limiting). These might even be used for the internal rate-limiting in some form, but afaik the current rate-limiting already prevents you from going over your limit anyways, so this point isn't very important I guess.

**Comment by EldoranDev** [comment]
I fully agree here.

The interesting part in this question is if @claudiowilson is still willing to maintain this project or if we should fork and maintain the project somewhere else.

**Comment by claudiowilson** [comment]
@EldoranDev I'm still very much willing to maintain this project, however I'm incredibly time constrained because it's my final semester at university. I see you actively comment and help with the issues on this library. Would you be open to becoming a maintainer? I can give you push access to the repository

**Comment by EldoranDev** [comment]
@claudiowilson I'm in my final year also, but I'd love to squeeze in some time for this project, so yes i would be open to become a a maintainer.

**Comment by Colorfulstan** [comment]
Closed as this will be integrated into #60
