### ISSUE TITLE
Error getting match 429

### ISSUE THREAD

**Issue by kfir124** [claudiowilson/LeagueJS#55]
Hi all, when I try to query for match timeline data I sometimes get error 429:

> ERROR: ERROR GETTING MATCH: 429 429

Sometimes it even happens on the first try, sometimes after 2-3 tries, basically it is completely random.

I do setup rate limit when initializing the leaguejs client:

```
LolApi.init(config.lolApiKey, 'na');
LolApi.setRateLimit(10, 500); 
```

Isn't the client shall ratelimit me and not let me get 429 errors? also why sometimes I get the 429 error on my first try after 60 minutes of riot api inactivity?

**Comment by Colorfulstan** [comment]
Its a problem on riot's side, sometimes you get random 429 / 503 errors bc of too much general traffic.
If you have set up the rate limiter to fit your quota you don't need to worry about those.
Just queue up retries (im doing up to 10 with 0.2 seconds delay and still some of the requests have to be queued up for later)

Can be closed
