### ISSUE TITLE
Current state: pending

### ISSUE THREAD

**Issue by iamnikiyo** [claudiowilson/LeagueJS#56]
Tengo un problema al pedir los datos de la partida en vivo de un invocador, cuando pido la información recibo: { state: 'pending' } dejo una captura del código, es bastante simple pero debería funcionar .

![p1](https://cloud.githubusercontent.com/assets/7115302/18283629/6fea87c4-7466-11e6-8ccf-fc577decff6a.PNG)
![p2](https://cloud.githubusercontent.com/assets/7115302/18283630/6fed8df2-7466-11e6-8b7c-123a63f765cb.PNG)

**Comment by EldoranDev** [comment]
Could you rewrite your question in English please so more people could help to fix your issue ?
