### ISSUE TITLE
{State: 'pending'} issue

### ISSUE THREAD

**Issue by iamnikiyo** [claudiowilson/LeagueJS#57]
I have a problem when ordering data of a live game Summoner, when I ask for the information receipt: {state: 'pending'} leave a screenshot of the code is pretty simple but it should work.

![p1](https://cloud.githubusercontent.com/assets/7115302/18355767/7c32ced0-75ea-11e6-8891-b497bed69ff8.PNG)
![p2](https://cloud.githubusercontent.com/assets/7115302/18355768/7c374208-75ea-11e6-995f-73d8c5c15bc4.PNG)

**Comment by EldoranDev** [comment]
getCurrentGame should return a promise so you should use .then(callback) like you did with Summoner.getByName.

**Comment by iamnikiyo** [comment]
Thanks @EldoranDev , was my fault no use .then(callback) :D
