### ISSUE TITLE
Rate limit should be per-region, not global

### ISSUE THREAD

**Issue by twillard** [claudiowilson/LeagueJS#63]
From developer.riotgames.com:

"Note that rate limits are enforced per region. For example, with the above rate limit, you could make 10 requests every 10 seconds to both NA and EUW endpoints simultaneously."

It would be great if this lib could support per-region rate limits, instead of a global limit.

**Comment by EldoranDev** [comment]
I will integrate this in https://github.com/claudiowilson/LeagueJS/pull/60.
Additonally I'll look into integrating the changes in the legacy version later today.

**Comment by Colorfulstan** [comment]
Will be the case with the rework (https://github.com/claudiowilson/LeagueJS/pull/65/commits/754dceb45762518c7436d51c0d4010428a936095), can be closed

**Comment by Colorfulstan** [comment]
#65

**Comment by Colorfulstan** [comment]
rate limit is used per region on the (rework)[https://www.npmjs.com/package/leaguejs] - rework is not backwards compatible without some refactoring though
